name: dart_fix_hints
description: A MCP server that provides typical fixes for given Dart/Flutter lint errors.
version: 0.0.1
repository: https://github.com/fujidaiti/dart-fix-hints.git

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  dart_mcp: ^0.3.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  stream_channel: ^2.1.2
